version: '3.7'
services:
    app:
        build:
            args:
                user: ${USER}
                uid: 1000
            context: ./
            dockerfile: ./docker/Dockerfile
        image: trouter
        command: php -S 0.0.0.0:8000 -t public
        ports:
            - 8000:8000
        container_name: trouter-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - trouter
networks:
    trouter:
        driver: bridge